#server:
#  port: 8989
#
#spring:
#  config:
#    activate:
#      on-profile: local
#
#  datasource:
#    url: jdbc:mariadb://database:3306/gopang_item
#    username: root
#    password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    properties:
#      hibernate:
#        hibernate:
#        "[format_sql]": true
#        "[user_sql_comments]": true
#        "[highlight_sql]": true
#        "[hbm2ddl.auto]": update
#    open-in-view: true
#    show-sql: true